@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node4 as "" {
   dependencies: 
   operations: 
}
class node5 as "" {
   dependencies: 
   operations: 
}
class node6 as "" {
   dependencies: 
   operations: 
}
class node10 as "" {
   dependencies: 
   operations: 
}
class node27 as "" {
   dependencies: 
   operations: 
}
class node54 as "" {
   dependencies: 
   operations: 
}
class node71 as "" {
   initial: 
   dependencies: 
   operations: 
}
class node72 as "main.admin.CategoryAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   fieldsets: 
}
class node40 as "main.admin.CustomerAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   fieldsets: 
}
class node1 as "main.admin.ManufacturerAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   fieldsets: 
}
class node61 as "main.admin.OrderAdmin" {
   list_display: 
   search_fields: 
   inlines: 
   fieldsets: 
}
class node33 as "main.admin.OrderItemAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   fieldsets: 
}
class node35 as "main.admin.OrderItemInline" {
   model: 
   extra: 
   fields: 
}
class node30 as "main.admin.ProductAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   list_editable: 
   fieldsets: 
}
class node38 as "main.admin.ReviewAdmin" {
   list_display: 
   search_fields: 
   list_filter: 
   ordering: 
   fieldsets: 
   readonly_fields: 
}
class node60 as "main.apps.MainConfig" {
   default_auto_field: 
   name: 
}
class node63 as "main.forms.CartItemForm" {
   CartItemForm.Meta: 
}
class node43 as "main.forms.CategoryForm" {
   CategoryForm.Meta: 
}
class node2 as "main.forms.CustomerForm" {
   CustomerForm.Meta: 
}
class node48 as "main.forms.LoginForm" {
   username: 
   password: 
}
class node57 as "main.forms.ManufacturerForm" {
   ManufacturerForm.Meta: 
}
class node13 as "main.forms.OrderForm" {
   OrderForm.Meta: 
}
class node67 as "main.forms.OrderItemForm" {
   OrderItemForm.Meta: 
}
class node55 as "main.forms.ProductForm" {
   ProductForm.Meta: 
}
class node46 as "main.forms.RegistrationForm" {
   username: 
   email: 
   password1: 
   password2: 
   RegistrationForm.Meta: 
}
class node52 as "main.forms.ReviewForm" {
   ReviewForm.Meta: 
}
class node8 as "main.models.CartItem" {
   user: 
   product: 
   quantity: 
   price: 
   CartItem.Meta: 
   __str__(self): 
}
class node66 as "main.models.Category" {
   name: 
   description: 
   Category.Meta: 
   __str__(self): 
}
class node45 as "main.models.Customer" {
   first_name: 
   last_name: 
   email: 
   phone: 
   address: 
   Customer.Meta: 
   __str__(self): 
}
class node25 as "main.models.Manufacturer" {
   name: 
   country: 
   website: 
   Manufacturer.Meta: 
   __str__(self): 
}
class node39 as "main.models.Order" {
   buyer_firstname: 
   buyer_surname: 
   comment: 
   delivery_address: 
   total_price: 
   user: 
   Order.Meta: 
   __str__(self): 
}
class node58 as "main.models.OrderItem" {
   order: 
   product: 
   quantity: 
   OrderItem.Meta: 
   __str__(self): 
}
class node70 as "main.models.Product" {
   name: 
   description: 
   price: 
   photo: 
   is_exists: 
   manufacturer: 
   category: 
   Product.Meta: 
   __str__(self): 
}
class node7 as "main.models.Review" {
   product: 
   customer: 
   rating: 
   comment: 
   created_at: 
   Review.Meta: 
   __str__(self): 
}
class node14 as "main.views.CartItemCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node49 as "main.views.CartItemDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node65 as "main.views.CartItemDetailView" {
   model: 
   template_name: 
}
class node36 as "main.views.CartItemListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node69 as "main.views.CartItemUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node23 as "main.views.CategoryCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node16 as "main.views.CategoryDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node32 as "main.views.CategoryDetailView" {
   model: 
   template_name: 
}
class node64 as "main.views.CategoryListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node34 as "main.views.CategoryUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node73 as "main.views.CustomerCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node37 as "main.views.CustomerDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node47 as "main.views.CustomerDetailView" {
   model: 
   template_name: 
}
class node51 as "main.views.CustomerListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node22 as "main.views.CustomerUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node0 as "main.views.ManufacturerCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node29 as "main.views.ManufacturerDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node21 as "main.views.ManufacturerDetailView" {
   model: 
   template_name: 
}
class node41 as "main.views.ManufacturerListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node53 as "main.views.ManufacturerUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node68 as "main.views.OrderCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node62 as "main.views.OrderDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node31 as "main.views.OrderDetailView" {
   model: 
   template_name: 
}
class node19 as "main.views.OrderItemCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node26 as "main.views.OrderItemDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node56 as "main.views.OrderItemDetailView" {
   model: 
   template_name: 
}
class node59 as "main.views.OrderItemListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node3 as "main.views.OrderItemUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node12 as "main.views.OrderListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node18 as "main.views.OrderUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node20 as "main.views.ProductCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node24 as "main.views.ProductDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node44 as "main.views.ProductDetailView" {
   model: 
   template_name: 
}
class node42 as "main.views.ProductListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node17 as "main.views.ProductUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node9 as "main.views.ReviewCreateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}
class node50 as "main.views.ReviewDeleteView" {
   model: 
   template_name: 
   success_url: 
}
class node28 as "main.views.ReviewDetailView" {
   model: 
   template_name: 
}
class node15 as "main.views.ReviewListView" {
   model: 
   template_name: 
   context_object_name: 
}
class node11 as "main.views.ReviewUpdateView" {
   model: 
   form_class: 
   template_name: 
   success_url: 
}

@enduml
