# Generated by Django 5.2.3 on 2025-11-20 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import textwrap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, verbose_name='Сообщение лога')),
                ('table', models.TextField(blank=True, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Лог',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название производителя')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(null=0, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('delivery_address', models.CharField(default='', max_length=150, verbose_name='Адрес доставки')),
                ('total_price', models.FloatField(default=0, verbose_name='Итог')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, default='Нет описания', max_length=1024, null=True, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='products/')),
                ('is_exists', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        # === Триггеры для Category ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_category_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('category', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('category', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('category', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER category_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_category
                FOR EACH ROW EXECUTE FUNCTION log_category_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS category_log_trigger ON main_category;
                DROP FUNCTION IF EXISTS log_category_change();
            """)
        ),

        # === Триггеры для Manufacturer ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_manufacturer_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('manufacturer', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('manufacturer', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('manufacturer', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER manufacturer_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_manufacturer
                FOR EACH ROW EXECUTE FUNCTION log_manufacturer_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS manufacturer_log_trigger ON main_manufacturer;
                DROP FUNCTION IF EXISTS log_manufacturer_change();
            """)
        ),

        # === Триггеры для Customer ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_customer_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('customer', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('customer', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('customer', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER customer_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_customer
                FOR EACH ROW EXECUTE FUNCTION log_customer_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS customer_log_trigger ON main_customer;
                DROP FUNCTION IF EXISTS log_customer_change();
            """)
        ),

        # === Триггеры для Order ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_order_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('order', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('order', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('order', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER order_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_order
                FOR EACH ROW EXECUTE FUNCTION log_order_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS order_log_trigger ON main_order;
                DROP FUNCTION IF EXISTS log_order_change();
            """)
        ),

        # === Триггеры для Product ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_product_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('product', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('product', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('product', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER product_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_product
                FOR EACH ROW EXECUTE FUNCTION log_product_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS product_log_trigger ON main_product;
                DROP FUNCTION IF EXISTS log_product_change();
            """)
        ),

        # === Триггеры для OrderItem ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_orderitem_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('orderitem', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('orderitem', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('orderitem', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER orderitem_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_orderitem
                FOR EACH ROW EXECUTE FUNCTION log_orderitem_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS orderitem_log_trigger ON main_orderitem;
                DROP FUNCTION IF EXISTS log_orderitem_change();
            """)
        ),

        # === Триггеры для CartItem ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_cartitem_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('cartitem', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('cartitem', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('cartitem', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER cartitem_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_cartitem
                FOR EACH ROW EXECUTE FUNCTION log_cartitem_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS cartitem_log_trigger ON main_cartitem;
                DROP FUNCTION IF EXISTS log_cartitem_change();
            """)
        ),

        # === Триггеры для Review ===
        migrations.RunSQL(
            sql=textwrap.dedent("""
                CREATE OR REPLACE FUNCTION log_review_change()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('review', 'INSERT', NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'UPDATE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('review', 'UPDATE id=' || NEW.id, NOW());
                        RETURN NEW;
                    ELSIF TG_OP = 'DELETE' THEN
                        INSERT INTO main_log ("table", "message", "created_at")
                        VALUES ('review', 'DELETE id=' || OLD.id, NOW());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER review_log_trigger
                AFTER INSERT OR UPDATE OR DELETE ON main_review
                FOR EACH ROW EXECUTE FUNCTION log_review_change();
            """),
            reverse_sql=textwrap.dedent("""
                DROP TRIGGER IF EXISTS review_log_trigger ON main_review;
                DROP FUNCTION IF EXISTS log_review_change();
            """)
        ),
    ]
