# Generated by Django 5.2.2 on 2025-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_photo_alter_review_product_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_firstname',
            field=models.CharField(default='', max_length=150, verbose_name='Имя покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_surname',
            field=models.CharField(default='', max_length=150, verbose_name='Фамилия покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=150, verbose_name='Адрес доставки'),
        ),
    ]
