# Generated by Django 5.2.3 on 2025-06-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
